<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Bang.$(MSBuildProjectName)</AssemblyName>
    <RootNamespace>Bang.$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
  </PropertyGroup>

</Project>
